spring:
  application:
    name: SupHernova

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    org.hibernate.SQL: debug

openai:
  api:
    key: ${OPENAI_API_KEY:}
    url: https://api.openai.com/v1/chat/completions
    model: gpt-4o-mini

app:
  stt:
    base-url: ${STT_BASE_URL:http://localhost:8001}
  tts:
    base-url: ${TTS_BASE_URL:http://localhost:8002}
  internal:
    base-url: ${INTERNAL_BASE_URL:http://localhost:8080}
    token: ${INTERNAL_TOKEN}
  storage:
    audio-base-path: ${AUDIO_STORAGE_PATH:./storage/audio}
